---
version: 0.1.0
name: class-profiler
authors:
  - Matthew Greenfield
emails: 
  - mattgreenfield1@gmail.com
summary: Quickly benchmark speed and profile memory of specific or all methods within a class
description: |
  TBD
homepage: https://github.com/omgreenfield/class-profiler
license: MIT
required_ruby_version: '>= 2.7.0' # I don't remember why I picked this version
metadata:
  homepage_uri: https://github.com/omgreenfield/class-profiler
  rubygems_mfa_required: 'true'
